apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cattery.fullname" . }}
  labels:
    {{- include "cattery.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "cattery.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        cattery/config-checksum: {{ .Values.config | toYaml | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cattery.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "cattery.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - server
            - -c
            - /etc/cattery/config.yaml
          ports:
            - name: http
              containerPort: {{ regexReplaceAll ".*:" .Values.config.server.listenAddress "" | int }}
              protocol: TCP
            {{- if .Values.config.server.statusListenAddress }}
            - name: status
              containerPort: {{ regexReplaceAll ".*:" .Values.config.server.statusListenAddress "" | int }}
              protocol: TCP
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /status
              port: {{ include "cattery.probePort" . }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /status
              port: {{ include "cattery.probePort" . }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/cattery/config.yaml
              subPath: config.yaml
              readOnly: true
            {{- range $name, $spec := .Values.secretFiles }}
            - name: secret-file-{{ $name }}
              mountPath: {{ $spec.mountPath }}
              subPath: {{ default "content" $spec.existingSecretKey }}
              readOnly: true
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "cattery.fullname" . }}-config
        {{- range $name, $spec := .Values.secretFiles }}
        - name: secret-file-{{ $name }}
          secret:
            {{- if $spec.existingSecret }}
            secretName: {{ $spec.existingSecret }}
            {{- else }}
            secretName: {{ include "cattery.fullname" $ }}-file-{{ $name }}
            {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
