{{- range $name, $spec := .Values.secretFiles }}
{{- if $spec.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cattery.fullname" $ }}-file-{{ $name }}
  labels:
    {{- include "cattery.labels" $ | nindent 4 }}
type: Opaque
data:
  content: {{ $spec.value | toString | b64enc }}
{{- end }}
{{- end }}
