FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    git dotnet-runtime-8.0 golang-go tar curl

WORKDIR /action-runner

ARG RUNNER_VERISON='2.333'
ENV RUNNER_VERISON=$RUNNER_VERISON

RUN curl -sL -o actions-runner-linux-x64-${RUNNER_VERISON}.0.tar.gz https://github.com/actions/runner/releases/download/v${RUNNER_VERISON}.0/actions-runner-linux-x64-${RUNNER_VERISON}.0.tar.gz
RUN ls -al
RUN tar xzf ./actions-runner-linux-x64-${RUNNER_VERISON}.0.tar.gz

WORKDIR /cattery-agent

COPY . .

RUN ls -al /action-runner
RUN ls -al /cattery-agent
RUN ls -al .


RUN cd src && go build -o /action-runner/cattery/cattery