server:
  listenAddress: "0.0.0.0:5137"
  advertiseUrl: https://cattery.my-org.com

database:
  uri: mongodb://localhost:27017/cattery
  database: cattery

github:
  - name: paritytech-stg
    appId: 123456
    installationId: 654321
    privateKeyPath: path/to/github-private-key.pem
    webhookSecret: my-webhook-secret

  - name: paritytech
    appId: 123456
    installationId: 654321
    privateKeyPath: path/to/github-private-key.pem
    webhookSecret: my-webhook-secret

providers:
  - name: docker-local
    type: docker
    catteryUrl: http://host.containers.internal:5137 # example for podman

  - name: gce-stg
    type: google
    project: my-gcp-project
    credentialsFile: path/to/credentials.json

trayTypes:
  - name: cattery-tiny
    provider: docker-local
    shutdown: false
    runnerGroupId: 3
    githubOrg: My-Github-Org
    config:
      image: cattery-runner-tiny:latest

  - name: cattery-gce
    config:
      instanceTemplate: global/instanceTemplates/<instance-template>
      machineType: e2-standard-2
      project: my-gcp-project
      zone: us-west1-a
    extraMetadata:
      # can be: version (0.0.2), server (to download binary from server) or a commit hash
      cattery-agent-version: 0.0.4
      # cattery-agent-version: 13d197aa1e73db09514772e55794b3a0f9b7952b
    githubOrg: My-Github-Org
    maxTrays: 3 # max number of VMs of this type
    provider: gce
    runnerGroupId: 3 # check in github org settings -> Runner groups
    shutdown: true
