server:
  listenAddress: "0.0.0.0:5137"
  advertiseUrl: https://cattery.my-org.com

database:
  uri: mongodb://localhost:27017/cattery

github:
  - name: paritytech-stg
    appId: 123456
    installationId: 654321
    privateKeyPath: path/to/github-private-key.pem
    webhookSecret: my-webhook-secret

  - name: paritytech
    appId: 123456
    installationId: 654321
    privateKeyPath: path/to/github-private-key.pem
    webhookSecret: my-webhook-secret

providers:
  - name: docker-local
    type: docker
    catteryUrl: http://host.containers.internal:5137 # example for podman

  - name: gce-stg
    type: google
    project: parity-ci-2024
    credentialsFile: path/to/credentials.json

trayTypes:
  - name: cattery-tiny
    provider: docker-local
    shutdown: false
    runnerGroupId: 3
    githubOrg: paritytech
    config:
      image: cattery-runner-tiny:latest

  - name: cattery-gce
    provider: gce-stg
    shutdown: true
    runnerGroupId: 3
    githubOrg: paritytech-stg
    config:
      namePrefix: cattery-stg
      project: parity-ci-2024
      zone: europe-west1-d
      machineType: e2-standard-4
      preemptible: true
      network: <network-url>
      subnetwork: <subnetwork-url>
