name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    runs-on: cattery-gce
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-replica-set: rs0
          mongodb-port: 27017

      - name: run tests
        run: go test -C src ./...
